### ISSUE TITLE
Iridium Drill recipe

### ISSUE THREAD

**Issue by xJon** [kappa-maintainer/ElectroMagicToolsClassic#1]
Not sure if I’m missing anything, but the Iridium Drill is the only item without a recipe showing in JEI.
Perhaps it's not intended to be an item or it is unfinished?

**Comment by kappa-maintainer** [comment]
The recipe was manually commented in the source, I guess the author didn't like non-crossover content
Do you still want it?

**Comment by xJon** [comment]
Oh I see, in this case never mind then.
