### ISSUE TITLE
Obsidian pillars no longer generate

### ISSUE THREAD

**Issue by xJon** [kappa-maintainer/ElectroMagicToolsClassic#15]
I assume that the fix of https://github.com/kappa-maintainer/ElectroMagicToolsClassic/commit/c4bd3ad5e8d0109049680fd10793d43e38070945 also broke their generation in the Overworld somehow.
Downgrading to `0.0.15` immediately "resolves" this (but introduces the other issues).

**Comment by kappa-maintainer** [comment]
`getTopSolidOrLiquidBlock` is broken, for some reason it can only get air block, which stop any pillar from generation

**Comment by kappa-maintainer** [comment]
Try 0.0.18

**Comment by xJon** [comment]
@kappa-maintainer Thank you so much for the quick response, however oddly enough I cannot find any pillars in the Overworld with `0.0.18` as well.

**Comment by xJon** [comment]
This was resolved in `0.0.20`.
