### ISSUE TITLE
Can't charge 3 Chainsaw items

### ISSUE THREAD

**Issue by xJon** [kappa-maintainer/ElectroMagicToolsClassic#18]
![image](https://github.com/user-attachments/assets/a06e9399-7c21-42b3-af64-4ab841f1ea8e)
Neither are accepted in an MFSU.
All of the other mod's rechargeable items are accepted.

**Comment by kappa-maintainer** [comment]
Weissmoon forgot to override methods providing tier...

**Comment by kappa-maintainer** [comment]
Try 0.0.21

**Comment by xJon** [comment]
Can confirm it's fixed!
