### ISSUE TITLE
Rechargeable Boots of the Traveller round-up their charge on re-equip

### ISSUE THREAD

**Issue by xJon** [kappa-maintainer/ElectroMagicToolsClassic#19]
(Originally reported over https://github.com/xJon/Tekkit-SMP/issues/12)
Reproducible with all 3 kinds.

https://github.com/user-attachments/assets/6bd83c28-ed96-4b72-b819-b01b77c97784

**Comment by kappa-maintainer** [comment]
Couldn't find what's causing this, need more test

**Comment by xJon** [comment]
@kappa-maintainer How can I help testing it more?

**Comment by kappa-maintainer** [comment]
I guess ic2c can't handle EU numbers can't divide by 10 well and will try to fix any wrong numbers
So in 0.0.22 walking with those boots will not cost EU and it seems work?

**Comment by xJon** [comment]
If there's no EU cost when walking, what does cost EU? Only jumping?
Maybe instead make it so it costs 10 EU to walk but not every tick?

**Comment by kappa-maintainer** [comment]
Jumping, falling and reducing damage
As for moving faster, you can imagine it as the function of Boots of the Traveller

**Comment by xJon** [comment]
Hmm, but the Boots of the Traveller don't give you movement speed without Vis.

**Comment by kappa-maintainer** [comment]
Just test it with 0.0.22 in game and see if it is op

**Comment by xJon** [comment]
Yeah, I think it's quite overpowered:
- You can just run long distances without jumping (thanks to the higher step height) and as long as you only go up, you don't spend any energy
- With the standard Electric boots (with 10000 EU storage), you can't spend any energy?

**Comment by kappa-maintainer** [comment]
Checking implementation in gtnh version, it seems weissmoon used a dumb way

**Comment by xJon** [comment]
Oh right, referencing GTNH's version is a good idea...

**Comment by kappa-maintainer** [comment]
It seems:
- GTNH fork doesn't discharge when walking, I will check it in game
- Discharge 1000 EU per x meter walked is dumb to implement, the best solution is to figure out the root cause of round up behavior

**Comment by xJon** [comment]
@Speiger Do you have any input about this?
> ic2c can't handle EU numbers can't divide by 10 well and will try to fix any wrong numbers

**Comment by kappa-maintainer** [comment]
This line is always commented, but the problem somehow got fixed after I switched to armor tick

**Comment by xJon** [comment]
@kappa-maintainer

https://github.com/user-attachments/assets/e1723094-c5b9-4af4-915b-208c13e55c08

**Comment by kappa-maintainer** [comment]
Forgot to test under survival
Now it loves to round up to weird numbers like 999726, wtf

**Comment by Speiger** [comment]
@kappa-maintainer / @xJon that is a client/server desync. That means the energy was taken on the client side but not server side!

**Comment by xJon** [comment]
@kappa-maintainer You mean why only in survival mode?

**Comment by xJon** [comment]
Maybe check whether it uses some client-side functions or events?

**Comment by xJon** [comment]
@kappa-maintainer As you said in Discord in `0.0.24` all of the Electric Boots of the Traveller no longer give bonuses while walking, which is a problem as there's no parity with the base item, so in some ways it is a downgrade

Apart from that I can confirm the original issue is resolved!

**Comment by Speiger** [comment]
@kappa-maintainer you could just call the drain function on the server  side and use the "canUse" function on the client sided

**Comment by xJon** [comment]
@kappa-maintainer It can still occur to an less significant degree using `0.0.26` 😢

https://github.com/user-attachments/assets/ebba3c75-ec08-4ea1-89d2-082f10cb9f95
