### ISSUE TITLE
Nanosuit + Quantum Boots of the Traveller cause fall damage

### ISSUE THREAD

**Issue by xJon** [kappa-maintainer/ElectroMagicToolsClassic#20]
(Originally reported over https://github.com/xJon/Tekkit-SMP/issues/13)

![image](https://github.com/user-attachments/assets/51c4c493-9b78-4f04-b179-b5a536d02d10)

**Comment by kappa-maintainer** [comment]
The author use a wrong event for that, I guess he didn't even test

**Comment by xJon** [comment]
This was fixed by https://github.com/kappa-maintainer/ElectroMagicToolsClassic/commit/6439e206cb571624c207bf3dbd7350eb7b613638 🚀
