### ISSUE TITLE
World freeze in Mo' Creatures Wyvern Lair

### ISSUE THREAD

**Issue by xJon** [kappa-maintainer/ElectroMagicToolsClassic#7]
![image](https://github.com/kappa-maintainer/ElectroMagicToolsClassic/assets/8945347/3706e93c-b39f-4413-9f95-d7542aac2119)

`net.minecraft.world.World.func_175623_d `

https://github.com/kappa-maintainer/ElectroMagicToolsClassic/blob/master/src/main/java/weissmoon/electromagictools/world/ObsidianPillarGenerator.java

**Comment by kappa-maintainer** [comment]
Bad coding
I will take a look later
