### ISSUE TITLE
0.0.16 Obsidian Tile block broken texture

### ISSUE THREAD

**Issue by xJon** [kappa-maintainer/ElectroMagicToolsClassic#9]
![image](https://github.com/kappa-maintainer/ElectroMagicToolsClassic/assets/8945347/596cf4af-47fe-450b-853a-f8b01ee07b81)

(Does not occur on 0.0.15)

**Comment by xJon** [comment]
It definitely catches the player's attention
![image](https://github.com/kappa-maintainer/ElectroMagicToolsClassic/assets/8945347/ef7db783-fe44-4a69-8987-3cdde0e2e7f7)

**Comment by kappa-maintainer** [comment]
The repository didn't even include these texture, wtf
I will copy them from 0.0.15

**Comment by xJon** [comment]
@kappa-maintainer Comparing the assets included in the repository and the `0.0.15` release, there are more differences:
![image](https://github.com/kappa-maintainer/ElectroMagicToolsClassic/assets/8945347/1c92d9b8-a59d-496b-8229-bd93d7e5b290)

**Comment by xJon** [comment]
Resolved since `0.0.17`.
